apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
spec:
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-app
        image: 9673483686/helloworld
        ports:
        - containerPort: 80
